### ISSUE TITLE
Replacer is executed twice

### ISSUE THREAD

**Issue by ste101** [jweiland-net/replacer#11]
With this config in 10.4
```
  search {
    10 = Test
  }

  replace {
    10 = Test@
  }
```
I'm getting this result:
```Test@@```

**Comment by pascal20997** [comment]
Hope you are not using replacer in TYPO3 7 or 8 😅 . The new release fixes this problem by checking if the current page has some USER_INT plugins so either the hook before caching the page or the middleware (after USER_INT is processed) will be executed
