### ISSUE TITLE
Add regex example to documentation

### ISSUE THREAD

**Issue by ste101** [jweiland-net/replacer#12]
With this example I was able to replace a pattern only within a <p> tag.
Maybe a good start for others.
```
config.tx_replacer {
  enable_regex = 1
  search {
    10 = #<p(.*)>(.*)Test(.*)<\/p>#
  }

  replace {
    10 = <p$1>$2Test@$3</p>
  }
}
```

This link helped me a lot:
https://www.regextester.com/27540

**Comment by xerc** [comment]
https://regex101.com/
```
/(<p[^>]+>.*?)SEARCH(.*?<\/p>)/
```
```
$1REPLACE$2
```

**Comment by pascal20997** [comment]
Thank you guys for this great idea :)
