### ISSUE TITLE
Question/Idea: Is it possible to delimit replacement to certain parts of the code

### ISSUE THREAD

**Issue by G16Kiel** [jweiland-net/replacer#3]
Case:
Replacement of "Word-Otherword" to "nobr Word-Otherword nobr" or "WordNONBREAKINGHYPHENOtherword" works.
But if we find this in the HEAD or in HTML-Parts like IMG-Description, it will be replaced there too.
In my case it not possible to special-tag "Word-Otherword". What we know is:
It is always in the BODY an always somewhere inside a DIV or H-Tag or P or LI

**Comment by pascal20997** [comment]
Maybe adding the possibility to use a regex would fix this problem.
Let´s think about solutions.
One solution could be to use preg_replace for a replacement via regex.
The other solution could be to use preg_match to get the matching content and then to execute a str_replace using the match as search string.

What do you think?

**Comment by xerc** [comment]
> preg_replace

ref. [github.com/MaxServ/t3ext-replacecontent](https://github.com/MaxServ/t3ext-replacecontent/blob/master/Classes/Hook/ContentPostProcAll.php#L50)

**Comment by ste101** [comment]
Please, could you give an example how to use regex to replace pattern only in a tag like body p and so on?

**Comment by xerc** [comment]
there might be a one-line soulution.. but its more readable if you replace in seperate function
`/(<([a-z]+)[^>]+?>)([^<]+?)<\/\2>/g` =>> '<$1>'.repl.(what,with,$3).'</$2>' (pseudocode)

**Comment by ste101** [comment]
Thank you for your response but for me this is like suaheli ;-)
Is there a way to get a working example for the <p> tag?

**Comment by ste101** [comment]
I found a solution:
#12
