### ISSUE TITLE
TypeError: TypoScriptHelper::getContentObjectRenderer() returns null on shortcut pages

### ISSUE THREAD

**Issue by christophlehmann** [jweiland-net/replacer#37]
TYPO3 v12
Replacer v3.0.3

<img width="1128" alt="Bildschirmfoto 2024-01-16 um 21 23 10" src="https://github.com/jweiland-net/replacer/assets/4953689/36c92259-d3bf-4742-b93f-1f231d9e28f6">

**Comment by kszymukowicz** [comment]
From my logs looks like this problem is also on redirect after powermail form submit.
