### ISSUE TITLE
replacer fails in Workspaces 

### ISSUE THREAD

**Issue by co-operate** [jweiland-net/replacer#7]
Trying to save a substitution category or a substitution term in another than the Live workspace fails with the following error:

> These fields of record 1 in table "tx_content_replacer_term" have not been saved correctly: pid! The values might have changed due to type casting of the database.

**Comment by pascal20997** [comment]
Hey @co-operate, sorry for the late response. The field 'tx_content_replacer_term' is part of the EXT:content_replacer from Stefan Galinski, this is the EXT:replacer from jweiland.net. You may open an issue ticket right here: https://gitlab.sgalinski.de/typo3/content_replacer 😄.
