### ISSUE TITLE
Problems with Typo3 10.4.6

### ISSUE THREAD

**Issue by daniel-mi** [jweiland-net/replacer#9]
Hello,

since I updated to Typo3 10 the plugin does not work anymore.
After modifying the following line it runs again without problems.

File: replacer/ext_localconf.php

old:
`$TYPO3_CONF_VARS['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-output']['z9_replacer'] = \JWeiland\Replacer\Hooks\TypoScriptFrontendController::class . '->contentPostProcAll';`

new:
`$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-output']['z9_replacer'] = \JWeiland\Replacer\Hooks\TypoScriptFrontendController::class . '->contentPostProcAll';`

**Comment by pascal20997** [comment]
You're right, I fixed that issue and will release v 1.5.1 in a few minutes. Thanks
